---
name: release-drafter

on:
  push:
    branches: [develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  draft:
    uses: nolte/gh-plumbing/.github/workflows/reusable-release-drafter.yml@v1.1.18
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
