---
name: release-cd-refresh-master

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  refresh:
    uses: nolte/gh-plumbing/.github/workflows/reusable-release-cd-refresh-master.yml@v1.1.19
    with:
      target_branch: main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
